"""Asynchronous reconstruction orchestration API endpoints."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, status

from backend.app.core.config import settings
from backend.app.reconstruction.orchestration.monitoring import monitoring
from backend.app.reconstruction.orchestration.pipeline_manager import pipeline_manager
from backend.app.reconstruction.schemas.api import (
    ReconstructionArtifactsResponse,
    StartReconstructionRequest,
    StartReconstructionResponse,
)
from backend.app.reconstruction.storage.datasets import registry as dataset_registry
from backend.app.tasks.reconstruction_tasks import capture_stage_task


router = APIRouter(prefix="/reconstruction", tags=["reconstruction"])


@router.post("/start", response_model=StartReconstructionResponse, status_code=status.HTTP_202_ACCEPTED)
async def start_reconstruction(request: StartReconstructionRequest) -> StartReconstructionResponse:
    """Create a reconstruction job and enqueue pipeline processing."""
    job = pipeline_manager.create_job(user_id=request.user_id, reconstruction_version="v2")
    if settings.RECONSTRUCTION_ASYNC_ENABLED:
        try:
            capture_stage_task.delay(job.id, request.image_urls, request.quality, request.object_type)
        except Exception:
            # Local fallback for environments without an active broker.
            capture_stage_task(job.id, request.image_urls, request.quality, request.object_type)
    else:
        capture_stage_task(job.id, request.image_urls, request.quality, request.object_type)
    return StartReconstructionResponse(job_id=job.id, status=job.status.value, stage=job.stage.value)


@router.get("/{job_id}")
async def get_reconstruction(job_id: str) -> dict:
    """Return full reconstruction job details."""
    job = pipeline_manager.get_job(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Reconstruction job not found")
    return job.model_dump()


@router.get("/{job_id}/status")
async def get_reconstruction_status(job_id: str) -> dict:
    """Return concise reconstruction status payload."""
    status_payload = pipeline_manager.get_job_status(job_id)
    if status_payload is None:
        raise HTTPException(status_code=404, detail="Reconstruction job not found")
    return status_payload


@router.get("/{job_id}/progress")
async def get_reconstruction_progress(job_id: str) -> dict:
    """Return current progress and event timeline for polling clients."""
    progress_payload = pipeline_manager.get_job_progress(job_id)
    if progress_payload is None:
        raise HTTPException(status_code=404, detail="Reconstruction job not found")
    return progress_payload


@router.get("/{job_id}/artifacts", response_model=ReconstructionArtifactsResponse)
async def get_reconstruction_artifacts(job_id: str) -> ReconstructionArtifactsResponse:
    """Return artifact references generated by reconstruction stages."""
    artifacts_payload = pipeline_manager.get_artifacts(job_id)
    if artifacts_payload is None:
        raise HTTPException(status_code=404, detail="Reconstruction job not found")
    return ReconstructionArtifactsResponse(**artifacts_payload)


@router.get("/{job_id}/confidence")
async def get_reconstruction_confidence(job_id: str) -> dict:
    """Return confidence breakdown and overall score."""
    job = pipeline_manager.get_job(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Reconstruction job not found")

    breakdown = {
        "geometry_confidence": job.confidence_breakdown.get("geometry", 0.0),
        "segmentation_confidence": job.confidence_breakdown.get("segmentation", 0.0),
        "material_confidence": job.confidence_breakdown.get("materials", 0.0),
        "overall_confidence": job.confidence_score or 0.0,
    }
    return breakdown


@router.get("/monitoring/metrics")
async def get_monitoring_metrics() -> dict:
    """Return pipeline performance and failure metrics."""
    return monitoring.snapshot()


@router.get("/datasets/snapshot")
async def get_dataset_snapshot() -> dict:
    """Return current dataset counts used for reconstruction moat-building."""
    return dataset_registry.snapshot()
